### ISSUE TITLE
Goals for week of 4/13

### ISSUE THREAD

**Issue by latazzajones** [latazzajones/Intro-to-Programming-Using-Ruby#1]
- [x] Add an outline from slide deck: https://docs.google.com/presentation/d/1v8uF4T4hr7OJTZrSv6NoUEQi5bMqWibYefjtgcIAzlA/edit#slide=id.g2f97140b2_0_6
- [x] Add some styling
- [x] Add Vaidehi's Bio
- [x] Add Natasha's Bio

**Comment by vaidehijoshi** [comment]
Added some styling and my bio!

**Comment by latazzajones** [comment]
look! I checked the boxes!
