### ISSUE TITLE
Goals for week of 5/4

### ISSUE THREAD

**Issue by vaidehijoshi** [latazzajones/Intro-to-Programming-Using-Ruby#2]
- [x] Create google form for application
- [ ] Create meetup page and advertise it!
- [x] Create slides for Day 1.
- [x] Create slides for Day 2.
- [x] Create slides for Day 3.
- [ ] Create slides for Day 4.
- [ ] Add code snippets.
- [ ] Add homework slides for each class.
- [ ] Set up virtual machine to test install for PC.
- [ ] Set up virtual machine to test install for Mac.

**Comment by latazzajones** [comment]
um - I'm closing this.

**Comment by vaidehijoshi** [comment]
sounds good! :)
